### PR TITLE
adding full URL if no selection specified

### PR DESCRIPTION
**Pull request by theparselmouth**
#28

### CODE REVIEW

**Comment by unitehenry** [comment]
insert-link

*not quite*

I didn't realize it, but it seems that this behavior is working correctly in chrome. If you want to use the browser variables (```isEdge```, ```isFirefox```, etc.) to make this functionality work in other browsers that would be helpful.

Also, this behavior isn't related to the ```pastedHtml```. Just in the event where the user click ```linkMenuButton``` to insert the link on a selected text.

**Comment by theparselmouth** [comment]
It's pretty late in my time zone. Will work on it tomorrow

**Comment by theparselmouth** [comment]
How do I do local testing for this editor ?

**Comment by unitehenry** [comment]
@theparselmouth Just follow the steps in [CONTRIBUTING](https://github.com/striven-erp/striven-editor/blob/master/CONTRIBUTING.md)

**Comment by theparselmouth** [comment]
Okay thank you 😁

**Pull request closed without merging**
