### PR TITLE
Improves browser detection by checking UA

### PR DESCRIPTION
**Pull request by waghcwb**
Closes: #41

### CODE REVIEW

**Comment by waghcwb** [comment]
@unitehenry,

We can now check for browser versions too, like this:
```js
this.browser.isChrome('77')
```

**Comment by unitehenry** [comment]
@waghcwb I am unsure of how User Agent testing is usually conducted, but I just wanted to verify that these changes are sure to be optimal and reliable.

Is this a standard way for checking the user's browser?

**Comment by waghcwb** [comment]
I think this is the better way to check the user's browser. I was looking in another libs that check the browser and all of them uses UA.

The UA is not 100% reliable because the user can change it with browser extensions, but only advanced users do that.

https://github.com/lancedikson/bowser/blob/master/src/parser-browsers.js
https://github.com/darcyclarke/Detect.js/blob/master/detect.js

**Comment by unitehenry** [comment]
@waghcwb I've looked into these packages as well, but I plan to leave the editor at *zero* dependencies. I agree that the UA is a better way to monitor the browser, but I just want to make sure that we have a reliable way of doing it.

I understand that it can easily be modified by the user, but I have no problems with that situation as the editor is just a client-side control. So my question is... If we check the browser with the way this PR suggests, will we always get the correct browser?

**Comment by waghcwb** [comment]
@unitehenry 

Yes, I caught  those regexes from popular and well tested repositories (+4k stars), so I think we can go this way.

**Comment by unitehenry** [comment]
@sanjogs What do you think about using this method for verifying the ```userAgent``` and checking the browser?

**Pull request merged**
