### PR TITLE
#50 Feature/react integration

### PR DESCRIPTION
**Pull request by goatfryed**
This pr introduces optional react integration requested in #50 

unlike knockout and vue integration, we require react as dependency in order to create the root div to mount the editor on.

If we add the react utils to our index.js, we could wrap them in a try/catch block, to create an optional dependency export, but this leads to unuseful warnings for users that don't develop with react.

Therefore, I've decided to not at the react integration to index.js for now.

Also note, that since the options are not meant to be changed on a given instance, I've decided against a base solution that would receive the options as props and instead provided a method, that creates a component based on a set of options.

I've also provided an hook and example, if users want to change options of their editor component.
We could add a more elaborate component that supports option change based on the example, but should discuss details regarding transfer of content, files and what else.

See the README.md for more. :)

### CODE REVIEW

**Comment by unitehenry** [comment]
@goatfryed Will be reviewing this soon. Thanks for the PR!

**Comment by unitehenry** [comment]
@goatfryed I really like the integration.

I feel like the integration documentation can be more streamlined.

```js
import React from 'react';
import { createEditor } from '@striven-erp/striven-editor/dist/react-integration'

const Editor = createEditor({toolbarBottom: true, minimal: true,});

const App = () => {
     return (
          <>
               <Editor />
          </>
    )
}
```

The hooks look great! I feel like this feels more practical for a "getting started" approach with integrating the editor for react. Also, have you tested this at all?

**Comment by goatfryed** [comment]
Hey @unitehenry,
I've tested the components in demo projects, with and without react and for react with and without create-react-app. Note, that for local development without create-react-app, you need to set resolve.symlinks = false in webpack when using npm link.

I thought about adding a demo project to the repo itself, but the structure isn't suitable yet. Should we move demo/* to demo/vue and add a demo/react project to this project?

I've updated the docs based on your suggestion

**Comment by unitehenry** [comment]
@goatfryed 

I think having multiple demos for different frameworks is great (```demo/vue```, ```demo/react```). Did you ever find an issue with multiple instances of React? I tried taking a crack at the react-striveneditor, but took a break after running into multiple instances of React and complaining hooks not being at the top level.

Would you know why this is? *just curious*

**Comment by goatfryed** [comment]
related to the npm link issue mentioned above, yeah, a couple of times. ^^
Let me provide you a demo folder and then pls try again. Maybe I missed something, but I also found it to be not to intuitive working with npm link and the react external settings.

**Comment by unitehenry** [comment]
@goatfryed 

I had had to something similar to this with the vue demo [here](https://github.com/striven-erp/striven-editor/blob/master/demo/vue.config.js). Maybe I will bootstrap another ```create-react-app``` and try this again. Once I get a working demo in my hands, I promise to merge this.

**Pull request merged**
